### ISSUE TITLE
Library is not compatible with Win11 SDK

### ISSUE THREAD

**Issue by TheStormN** [stephenegriffin/MAPIStubLibrary#12]
The functions `OpenTnefStream` and `OpenTnefStreamEx` have `WIN_NOEXCEPT` specifier in Win11 SDK with makes the current ones defined by mapiStubLibrary.cpp incompatible, resulting compile time errors.

I guess some ifdefs will be needed to keep compatibility between older and newer SDKs.

**Comment by stephenegriffin** [comment]
I have been trying, on multiple machines, to reproduce this, but cannot. Does it only repro when you build on Windows 11? All of my machines are on Windows 10.

**Comment by TheStormN** [comment]
@stephenegriffin The machine is not important in this case, the SDK version is the key. On my side it is reproducible with both Windows 10 and Windows 11. The specific SDK version is `10.0.22000.0`. If you have multiple SDKs installed, make sure that your testing environment is using the proper one.

**Comment by TheStormN** [comment]
https://github.com/stephenegriffin/MAPIStubLibrary/pull/13 seems to be fixing the issue, however it was not merged...

**Comment by namespace-github** [comment]
I have the same Problem

**mapistub.vcxproj:**
```
C2382: "OpenTnefStream"
C2382: "OpenTnefStreamEx"
C2382: "GetTnefStreamCodepage"
```

SDK-Version `10.0.22000.0`

Any Updates here?

**Comment by stephenegriffin** [comment]
@TheStormN @namespace-github Do you have specific repro steps for this error? I cannot make it reproduce. What I tried:

1. Visual Studio 2022
2. Right click mapistub
3. Retarget projects
4. 10.0.22000.0
5. OK
6. Right click mapistub
7. Rebuild
Expected: C2382 Errors
Actual: No errors

**Comment by hendrik-schneider** [comment]
@stephenegriffin 

- VS2022 (17.6.33801.468)
- SDK 10.0.22000.0

Compiling a native node-module with node-gyp@9.3.1 and node@18.16.0

With 2019 it worked for me:
`node-gyp rebuild --msvs_version=2019`

With 2019 it failed:
`node-gyp rebuild --msvs_version=2022`

```
mapiStubLibrary.cpp(1882,1): error C2382:  
"OpenTnefStream"
mapiStubLibrary.cpp(1897,1): error C2382:  
"OpenTnefStreamEx"
mapiStubLibrary.cpp(1945,1): error C2382:  
"GetTnefStreamCodepage"
```

**Comment by stephenegriffin** [comment]
@hendrik-schneider thanks for that. I've never used or heard of node-gyp before. I installed it but when I ran node-gyp rebuild --msvs_version=2019 I got an error "binding.gyp not found".

**Comment by stephenegriffin** [comment]
I think I may repro this with this binding.gyp:
```
{
  "targets": [
    {
      "target_name": "binding",
      'include_dirs': ['include'],
      "sources": [
          "library/mapiStubLibrary.cpp",
          "library/stubutils.cpp"
          ]
    }
  ]
}
```

**Comment by stephenegriffin** [comment]
Fixed by c827684

**Comment by hendrik-schneider** [comment]
Thank you very much for your super fast support. This fix solves the problem. 😀

**Comment by stephenegriffin** [comment]
@hendrik-schneider thanks for the repro tip - I couldn't test the proposed fixes before that
