### ISSUE TITLE
How do you use WrapCompressedRTFStreamEx?

### ISSUE THREAD

**Issue by amtopel** [stephenegriffin/MAPIStubLibrary#8]
Hi, is it possible to use `WrapCompressedRTFStreamEx` with this library?  It appears in `MapiStubLibrary.cpp`, but not in any headers.  But then the necessary structs `RTF_WCSINFO` and `RTF_WCSRETINFO` aren't defined anywhere.  So is `WrapCompressedRTFStreamEx` usable, and if so, how?  Thanks.

**Comment by stephenegriffin** [comment]
See usage in mfcmapi: https://github.com/stephenegriffin/mfcmapi/search?q=WrapCompressedRTFStreamEx&unscoped_q=WrapCompressedRTFStreamEx

**Comment by amtopel** [comment]
Thank you, but I'm unable to make the call succeed.  Per your mfcmapi code, I added this to the tope of my file:

```
struct RTF_WCSINFO
{
    ULONG size; // Size of the structure
    ULONG ulFlags;
    ULONG ulInCodePage;
    ULONG ulOutCodePage;
};

struct RTF_WCSRETINFO
{
    ULONG size;
    ULONG ulStreamFlags;
};

// Declaration missing from headers
STDAPI_(HRESULT)
    WrapCompressedRTFStreamEx(
        LPSTREAM pCompressedRTFStream,
        const RTF_WCSINFO* pWCSInfo,
        LPSTREAM* ppUncompressedRTFStream,
        RTF_WCSRETINFO* pRetInfo);

#define MAPI_NATIVE_BODY 0x00010000
#define pidExchangeXmitReservedMin	0x3FE0
#define PR_INTERNET_CPID PROP_TAG(PT_LONG, pidExchangeXmitReservedMin - 0x02)
```

And then after opening an Imessage (pMsg), I tried this:


```
    CComPtr<IStream> pCompressedStream;
    hr = pMsg->OpenProperty(PR_RTF_COMPRESSED,
                            &IID_IStream,
                            NULL,
                            NULL,
                            (LPUNKNOWN*)&pCompressedStream);
    if (FAILED(hr))
    {
        return hr;
    }

    LPSPropValue pPropVal;
    hr = HrGetOneProp(pMsg, PR_INTERNET_CPID, &pPropVal);
    if (FAILED(hr))
    {
        return hr;
    }

    CComPtr<IStream> pUncompressedStream;

    RTF_WCSINFO wcsinfo = { 0 };
    wcsinfo.size = sizeof(RTF_WCSINFO);
    wcsinfo.ulFlags = MAPI_NATIVE_BODY;
    wcsinfo.ulInCodePage = pPropVal->Value.ul;
    wcsinfo.ulOutCodePage = 0;

    RTF_WCSRETINFO wcsretinfo = { 0 };
    wcsretinfo.size = sizeof(RTF_WCSRETINFO);

    hr = WrapCompressedRTFStreamEx(pCompressedStream, &wcsinfo, &pUncompressedStream, &wcsretinfo);
```

But that final call to `WrapCompressedRTFStreamEx `never works.  Do you know what might be going wrong?  Thanks again for your help.

**Comment by stephenegriffin** [comment]
What version of outlook do you have installed? Which mapi binary are you loading and from what directory?

**Comment by amtopel** [comment]
I have Microsoft Outlook 2016 installed, and I currently link to `MapiStubLibrary.lib` inside the `MAPIStubLibrary-master\vs2017\MapiStubLibrary` directory (with different sub-directories depending debug/release and x64/x86).

I think I may be working from an earlier version of this repo, but I briefly updated to the latest version and encountered the same exact problem (I had to roll back to previous version because it led to some unforeseen linking errors from other libraries).

**Comment by stephenegriffin** [comment]
ok - but are you loading olmapi32.dll or mapi32.dll? Which path are you loading MAPI from? It sounds like maybe you're loading mapi32.dll instead of olmapi32.dll.

Also - what do you mean by "encountered the same problem" with MFCMAPI? MFCMAPI is already built to use WrapCompressedRTFStreamEx without making any changes. Just right click on PR_RTF_COMPRESSED and pick it off the menu.

**Comment by amtopel** [comment]
Hm, I just link to the .lib, and I guess I just always prayed for the best.  Are you supposed to also load something explicitly?  How do you load olmapi32.dll?  Thanks again for your help.

**Comment by stephenegriffin** [comment]
Somehow you didn't answer my question of which mapi32 module you loaded or where from. You can get this information from visual studio, process explorer, process monitor, etc.
